### ISSUE TITLE
Package is not up to date

### ISSUE THREAD

**Issue by zesterer** [flathub/net.veloren.veloren#1]
Hello, Veloren developer here. This package is quite out of date. We'd prefer, if possible, that our primary launcher (called 'Airshipper': https://github.com/Songtronix/Airshipper) be packaged instead such that users can play the most up-to-date version.

**Comment by Songtronix** [comment]
Unsure if packaging a launcher is great idea. Then I have another package to keep updated.

**Comment by Songtronix** [comment]
However that's not the big issue. Tim mentioned it would be bad because we ship pre build binaries which is completely against what flatpak is all about. See #meta for the discussion. I'll see if I can write a bot which updates this repo or will make a disclaimer in the Readme pointing out that's only the stable version. 
Let's discuss this in #Meta

**Comment by frzifus** [comment]
but do we want to update the flatpak version with every nightly build? isn't there a beta tag or something similar on flathub?

**Comment by Songtronix** [comment]
@tim77

**Comment by Songtronix** [comment]
> This isn’t meant to be used for nightly builds, but for releases that has some level of testing and are expected to mostly work and be usable to non-developer end-users.

https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

Looks like our best bet would be to have flatpak use stable releases and just note in the readme that multiplayer won't work.

**Comment by Songtronix** [comment]
Although on the automation side I found: https://github.com/flatpak/flat-manager

**Comment by tim77** [comment]
> Hello, Veloren developer here. This package is quite out of date.

Hello. `51126da1` is quite out of date? It was basically the latest Veloren build. After this there was just few commits which fixing toolchain and they are not related to Flatpak build. I checked 12H ago and there was no updates until you merged big portion today:
![DeepinScreenshot_select-area_20200424101417](https://user-images.githubusercontent.com/5614476/80185072-69c1d500-8614-11ea-9ca6-7ce7d973d883.png)

I am not forgot or something. :) For example my [Copr](https://copr.fedorainfracloud.org/coprs/atim/veloren/) builds is always updated 1-3 times per week and always up to day. There was a night and i was sleep. Thats why i ask for co-maintainership and @Songtronix already updated it. :tada: Not sure is completely automate building every commit is a best idea since sometimes users can get broken update.

> We'd prefer, if possible, that our primary launcher (called 'Airshipper': https://github.com/Songtronix/Airshipper) be packaged instead such that users can play the most up-to-date version.

Airshiper [packaged](https://github.com/gasinvein/flatpak-apps-staging/tree/com.songtronix.Airshipper/master) from the day one since we talk about it last time in Discord by @gasinvein 

Thats totally up on you as i already said and Flathub is all about upstream and their decisions, but i don't see any reason why Airshiper is better in any way then Flatpak build from sources and why should Flatpak updates lags behind Airshipper updates since devs have direct access to flatpak build.

But the reason why Flatpak build is better then pre-build binaries should be obvious i suppose. Flatpak build guarantees to work on any old and new mainstream linux distro, pre-built binaries mostly depend on luck. But Flatpak Airshiper should be fine too in this regards. And build from source vs pre-built binaries it's almost like free vs proprietary build TBH. but it's up to you, once again.

> Looks like our best bet would be to have flatpak use stable releases and just note in the readme that multiplayer won't work.

Dunno, imo multiplayer is really must have there even if game on early stage.

---

Note: i am sitting always in Discord now because of Veloren. :) So as i already said most important part there is update in time when breaking changes happens between server <-> client. And even this not a problem since devs can maintain Flatpak build and this is what i wanted from the beginning. And Flatpak community can always help if something happens.

---

Also we can lower to 0H update delay before new build pushed to repos. Now it's 3 hours, default. But this time could be useful too to test build for maintainers.

**Comment by barthalion** [comment]
> Although on the automation side I found: https://github.com/flatpak/flat-manager

It's a software for managing flatpak repositories, not automating updates. You should add generic git tag or commit checker to https://github.com/flathub/flatpak-external-data-checker/ if you want to go automation route, it's run every hour for apps with `x-external-data` defined.

**Comment by gasinvein** [comment]
I guess the best approach would be to stick with stable releases on flatpak `stable` branch (they're built from git `master` branch of this repo) and push nightly builds to flatpak `beta` branch (git `beta` branch).
Note that the Flathub Beta repo has to be added separately by users.

**Comment by zesterer** [comment]
> Hello. 51126da1 is quite out of date? It was basically the latest Veloren build.

Apologies, I'm going based on reports from users of the Flatpak package (we had someone yesterday that was having trouble connecting because their version was about 3 weeks out of date).

**Comment by gasinvein** [comment]
@zesterer This flatpak was published 8 days ago, how one could have 3 weeks old flatpak build?

**Comment by tim77** [comment]
Now it's fine anyway. Great update btw. As for auto update there some more variants: we can use `freedesktopsdk/sdk:19.08-x86_64` in Docker CI and ship 100% ABI-compatible binaries.

**Comment by Songtronix** [comment]
Did not even know that Airshipper gets packaged too. I guess going with @gasinvein's suggestion would be the correct way to do things.

**Comment by tim77** [comment]
> I guess going with @gasinvein's suggestion would be the correct way to do things.

From the beginning i thought [the same ](https://github.com/flathub/flathub/pull/1449#discussion_r408152963) that in stable flathub repo should be stable/tagged Veloren version. But in same time i believe users will be confused and ask [same questions](https://github.com/flathub/flathub/pull/1449#issuecomment-613442240). Maybe if there some tip in README or even better in-game menu which inform users that they should use nightly version if they want to play online and how they can get and install it.

**Comment by tim77** [comment]
JFYI: Veloren updating now automatically on Monday, Wednesday and Friday. Also switched to latest freedesktop 20.08 runtime.

Closing this one. But we still can continue discussing.
