### ISSUE TITLE
Can't connect since last update

### ISSUE THREAD

**Issue by tjaynl** [flathub/net.veloren.veloren#6]
Hello,

After the update is seems to give me a network error namely the following:
`Network error: Deserialize(lo(Custom{kind: UnexpectedEof, error:""}))`

Is this issue known and is there a way to fix it?

**Comment by tim77** [comment]
Hello. This will happens from time to time since game in alpha stage and because of constant updates client and server de-synced. This only affects official Veloren server, you still can play locally or on your own servers. Game updated automatically three times per week. And i often testing myself manually builds and if i found this issue i am doing manual update.

So in worst case you need to wait two days until auto update happens. But feel free to reopen this bug every time when you experiencing this issue and i'll try to hurry up with update. Closing for now since it was updated automatically and works now.
